# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0afb877171d56012cd87f9083ed5dd683552d74806df9c24d6be1177728f0e5927292f7d8f895b871ad8ba7a84e21d514ad2c87835c4c52f1e18861cdaf62096

test:
  secret_key_base: 3445881317be8a2190af0d684ecd3d417dc15c0e010933e066e2499e13e9fca5497d4228b970d0f5fbcc6e4cedb1eac566f9aa29595c1e48e2576f723492cf80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
